# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('wordid', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(db_index=True, default='crk', max_length=5)),
                ('wordform', models.CharField(db_index=True, max_length=200)),
                ('pos', models.CharField(max_length=12)),
                ('animacy', models.CharField(max_length=20)),
                ('object', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=20)),
                ('translation', models.CharField(max_length=40)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crk_drill.Lemma')),
            ],
        ),
    ]
