# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crk_drill', '0002_auto_20170810_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='object',
        ),
        migrations.AddField(
            model_name='word',
            name='gram_code',
            field=models.CharField(default='null', max_length=40),
        ),
    ]
