# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crk_drill', '0003_auto_20170811_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=40, unique=True)),
                ('pos', models.CharField(max_length=12)),
                ('animacy', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=5)),
                ('derivation', models.CharField(max_length=7)),
                ('grade', models.CharField(max_length=10)),
                ('case', models.CharField(max_length=5)),
                ('trans_anim', models.CharField(max_length=5)),
                ('mood', models.CharField(max_length=5)),
                ('personnumber', models.CharField(max_length=8)),
                ('preverb', models.CharField(max_length=8)),
                ('object', models.CharField(max_length=12)),
                ('polarity', models.CharField(max_length=5)),
                ('mode', models.CharField(max_length=7)),
                ('tense', models.CharField(max_length=5)),
                ('intentional_definite', models.CharField(max_length=5)),
                ('infinite', models.CharField(max_length=10)),
                ('attributive', models.CharField(max_length=5)),
                ('possessive', models.CharField(max_length=10)),
                ('distance', models.CharField(max_length=7)),
                ('subclass', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='animacy',
        ),
        migrations.AddField(
            model_name='lemma',
            name='trans_anim',
            field=models.CharField(default='change this', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='gram_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crk_drill.Tag'),
        ),
        migrations.AddField(
            model_name='course',
            name='lemmas',
            field=models.ManyToManyField(to='crk_drill.Lemma'),
        ),
    ]
