# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crk_drill', '0004_auto_20170906_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(default='namôya nisitotin', max_length=40),
        ),
    ]
