# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crk_drill', '0006_auto_20170907_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='string',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
